name: london-bikes-env # unique name for conda environment
channels: # Specifies the remote repositories where Conda will look for the packages
  - defaults  # referenced from bde/elt
  - conda-forge  # referenced from bde/elt
dependencies:
  # Core Configuration
  - python=3.11.14  # referenced from bde/elt  
  # Data Manipulation & Extraction
  - pandas=2.3.3  # referenced from bde/elt [EDA]
  - google-cloud-bigquery  # suggested by LLM [Query data from BigQuery]
  #- google-cloud-storage=3.4.1  # referenced from bde [Store data in Google Cloud Storage (GCS) as data lake]
  - google-cloud-storage=3.1.0  # Downgraded from 3.4.1 to 3.1.0 to satisfy dbt-bigquery (<3.2) compatibility
  - requests=2.32.5  # referenced from elt [External data sources via REST APIs]
  - pyarrow=21.0.0  # referenced from bde [Process Parquet files]
  # Data Warehouse & Transformation
  - python-duckdb=1.2.1  # referenced from bde [Work with DuckDB]
  - duckdb-engine=0.15.0  # referenced from bde [Work with DuckDB]
  - dbt-duckdb  # suggested by LLM [dbt with DuckDB]
  # if dbt-bigquery=1.10.3 is not required, we can upgrade google-cloud-storage from 3.1.0 to 3.4.1
  - dbt-bigquery=1.10.3  # referenced from elt [dbt perform transformation within BigQuery]
  # Data Quality & Analysis
  - sqlalchemy=2.0.43 # referenced from bde [Connection to data warehouse]
  - great-expectations=1.8.0  # referenced from elt [Data quality testing]
  - ipykernel=7.1.0  # referenced from elt [Run Jupyter Notebooks in conda environment]
  - pytest=8.4.2  # referenced from elt [Framework for managing testing Python scripts]
  # Serving & Visualisation
  - streamlit  # suggested by LLM [Visualisation]
  - seaborn=0.12.2  # referenced from elt [Visualisation]
  - matplotlib=3.10.7  # referenced from elt [Visualisation]
  # Utilities
  - python-dotenv=1.1.0  # referenced from elt [Manage environment variables e.g. service account keys]
  - pip=25.3  # referenced from elt [Python package manager]
  - pip:  # referenced from elt
      - meltano==4.0.8  # referenced from elt [ELT automation with data]
